### ISSUE TITLE
H264_Image_transport launch file does not generate output

### ISSUE THREAD

**Issue by suyash-narain** [clydemcqueen/h264_image_transport#7]
Hi,

I am trying to run h264_image_transport package on ROS2 Humble on linux ubuntu 20.04 focal. The package gets built without any errors but when i try to run it using the launch file as provided, I get the **cannot find a proper format for codec h264 error** as in the log provided below.

Steps followed:

after building the package and sourcing it
1. $ ros2 run image_transport republish h264 raw --ros-args -r in/h264:=/image_raw/h264 -r out:=/repub_raw
2. $ ros2 launch h264_image_transport example_launch.py

error log: 

> $ ~/h264_image_transport$ ros2 launch h264_image_transport example_launch.py 
> [INFO] [launch]: All log files can be found below /home/mtk/.ros/log/2023-01-30-18-03-47-364858-mtk-NUC11TNHv5-23289
> [INFO] [launch]: Default logging verbosity is set to INFO
> [INFO] [h264_cam_node-1]: process started with pid [23291]
> [INFO] [republish-2]: process started with pid [23293]
> [h264_cam_node-1] [INFO] [1675130627.850684398] [h264_cam_node]: Parameter input_fn: /dev/video0
> [h264_cam_node-1] [INFO] [1675130627.850843682] [h264_cam_node]: Parameter fps: 30
> [h264_cam_node-1] [INFO] [1675130627.850853585] [h264_cam_node]: Parameter size: 800x600
> [h264_cam_node-1] [INFO] [1675130627.850859103] [h264_cam_node]: Parameter frame_id: camera_frame
> [h264_cam_node-1] [INFO] [1675130627.850864616] [h264_cam_node]: Parameter camera_info_path: info.ini
> [h264_cam_node-1] [video4linux2,v4l2 @ 0x56370007a180] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
> [h264_cam_node-1] Assertion *codec_id != AV_CODEC_ID_NONE failed at src/libavdevice/v4l2.c:815
> [ERROR] [h264_cam_node-1]: process has died [pid 23291, exit code -6, cmd '/home/mtk/h264_image_transport/install/h264_image_transport/lib/h264_image_transport/h264_cam_node --ros-args -r __node:=h264_cam_node --params-file /tmp/launch_params_w6o2nsmy'].
> 

running the republish executable as it is generates no output. Launching the example_launch.py file afterwards or as standalone leads to generating **Assertion codec_id != AV_CODEC_ID_NONE failed at src/libavdevice/v4l2.c:815** error and no further output is generated.

**Comment by clydemcqueen** [comment]
I have not tested h264_image_transport on Humble + 20.04, but I expect it to work.

This is failing in the video4linux2 driver. It appears that there are no h264 plugins installed.

You might be able to fix this by re-installing the requirements:

~~~
sudo apt install libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev
~~~

You can search for encoders and decoders using ffmpeg:

~~~
ffmpeg -encoders | grep 264
~~~

**Comment by suyash-narain** [comment]
I tried re-installing the below arguments:
`sudo apt install libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev`

The output of encoder decoder search using ffmpeg was as below:

> ffmpeg -encoders | grep 264
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
 V..... libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V..... libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V..... h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... h264_omx             OpenMAX IL H.264 video encoder (codec h264)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)


But after running the h264_image_transport node again, i get the same error as before

> [h264_cam_node-1] [video4linux2,v4l2 @ 0x561f50a90500] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
[h264_cam_node-1] Assertion *codec_id != AV_CODEC_ID_NONE failed at src/libavdevice/v4l2.c:815
[ERROR] [h264_cam_node-1]: process has died [pid 29506, exit code -6, cmd '/home/mtk/h264_image_transport/install/h264_image_transport/lib/h264_image_transport/h264_cam_node --ros-args -r __node:=h264_cam_node --params-file /tmp/launch_params_kpaexek2'].

**Comment by clydemcqueen** [comment]
Can your camera encode H264? To list formats:
~~~
v4l2-ctl --list-formats
~~~

**Comment by clydemcqueen** [comment]
Yes, this node only works with cameras that support H264.

I think the correct way to work with non-encoding cameras would be to implement an H264 encoder in a subclass of image_transport::PublisherPlugin.

**Comment by suyash-narain** [comment]
alright, thank you
